services:
  controller:
    build: .
    restart: unless-stopped
    env_file: ./.env
    cap_add: [NET_ADMIN]
    sysctls: [net.ipv4.ip_forward=1, net.ipv4.conf.all.src_valid_mark=1]
    ports:
      - ${WS_PORT:-8443}:${WS_PORT:-8443}
    depends_on: [postgres]

  postgres:
    image: postgres:17
    expose: [5432]
    ports: [127.0.0.1:5432:5432]
    shm_size: 128mb
    restart: unless-stopped
    volumes: [postgres:/var/lib/postgresql/data]
    env_file: ./.env
    healthcheck:
      test: pg_isready --dbname="$$POSTGRES_DB" --username="$$POSTGRES_USER"
      interval: 5s
      timeout: 60s
      retries: 5
      start_period: 30s
      start_interval: 500ms

volumes:
  postgres:
